# This workflow builds a multi-arch Docker image and pushes it to GitHub Container Registry (GHCR)

name: Docker Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   lfs: true

      # --- Add this step to set up QEMU for multi-arch builds ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # --- Add this step to set up Docker Buildx ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # --- Specify target platforms ---
          platforms: linux/amd64,linux/arm64 # Add other platforms if needed (e.g., linux/arm/v7)
          # --------------------------------
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optional: Enable build caching (might need adjustments for multi-arch)
          # cache-from: type=gha
          # cache-to: type=gha,mode=max