# This workflow builds a multi-arch Docker image and pushes it to GitHub Container Registry (GHCR)

name: Docker Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          # --- Keep only the standard multi-arch compatible tags ---
          tags: |
            type=schedule
            type=ref,event=branch  # Will create 'main' and 'latest' (if main is default branch)
            type=ref,event=pr
            type=semver,pattern={{version}} # Will create vX.Y.Z
            type=semver,pattern={{major}}.{{minor}} # Will create vX.Y
            type=semver,pattern={{major}} # Will create vX
            type=sha # Will create sha-<shortsha>
          # --- Removed the non-functional {{arch}} patterns ---

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Use the standard tags
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
